name: Verify

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Audit
        run: npm audit --production
      - name: Lint
        run: npm run lint --if-present
      - name: Test
        run: npm run unit --if-present -- --coverage
      - name: Test results
        uses: IgnusG/jest-report-action@v2
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: test-check
